default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123
  host: localhost
  port: 3306

development:
  <<: *default
  database: driver_api_development

test:
  <<: *default
  database: driver_api_test

production:
  <<: *default
  database: driver_api_production
  username: driver_api
  password: <%= ENV['DRIVER_API_DATABASE_PASSWORD'] %>
